## Iris Dataset classification

## Task 01 :

This particular ML project is usually referred to as the “Hello World” of Machine Learning.
The iris flowers dataset contains numeric attributes, and it is perfect for beginners to learn
about supervised ML algorithms, mainly how to load and handle data. Also, since this is a small dataset,
it can easily fit in memory without requiring special transformations or scaling capabilities.

In [9]:
import sklearn
from sklearn.datasets import load_iris
iris = load_iris()

In [10]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [11]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

## Description of dataset


In [12]:
print(iris["DESCR"])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [13]:
print(iris["target_names"])

['setosa' 'versicolor' 'virginica']


In [14]:
print(iris["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [19]:
print(type(iris["data"]))

<class 'numpy.ndarray'>


In [20]:
iris["data"].shape

(150, 4)

In [22]:
iris["target"]   # 0 means setosa , 1 means versicolor and 2 means virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## training and testing

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris["data"],iris["target"], random_state = 10)

In [49]:
X_train

array([[7.7, 2.6, 6.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 2.7, 3.9, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [4.7, 3.2, 1.6, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3.6, 1.4, 0.1],
       [6.9, 3.1, 5.4, 2.1],
       [4.8, 3. , 1.4, 0.3],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [4.4, 3.2, 1.3, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [7.9, 3

In [50]:
X_train.shape

(112, 4)

In [51]:
X_test.shape


(38, 4)

## k nearest neighbour (KNN)

In [52]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=1)

In [53]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [54]:
import numpy as np
X_new = np.array([[5,2,1,3]])
X_new.shape

(1, 4)

In [55]:
# for prediction
prediction = knn.predict(X_new)
prediction

array([0])

In [56]:
iris["target_names"][prediction]


array(['setosa'], dtype='<U10')

In [57]:
## evaluating the model
knn.score(X_test, y_test)

0.9736842105263158

## Naive bayes classification

In [60]:
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train,y_train)

GaussianNB()

In [62]:
y_pred = nvclassifier.predict(X_test)
print(y_pred)

[1 2 0 1 0 1 1 1 0 1 1 2 1 0 0 2 1 0 0 0 2 2 2 0 1 0 1 1 1 2 1 1 2 2 2 0 2
 2]


In [65]:
y_compare = np.vstack((y_test,y_pred))
y_compare[:5, :]

array([[1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
        2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2],
       [1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
        2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2]])

In [70]:
## making the confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
print(cm)

[[11  0  0]
 [ 0 15  0]
 [ 0  0 12]]


In [74]:
## finding accuracy from the confusion matrix
a= cm.shape
corrPred=0
falsePred=0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred += cm[row,c]
        else:
            falsePred += cm[row,c]
print("correct prediction :", corrPred)
print("false prediction :", falsePred)
print("\nAccuracy of the naive bayes classification is  :", corrPred/(cm.sum()))

correct prediction : 38
false prediction : 0

Accuracy of the naive bayes classification is  : 1.0
